### ISSUE TITLE
npm bugs ng2-cytoscape

### ISSUE THREAD

**Issue by jaags** [michaelknoch/ng2-cytoscape#2]

**Comment by d3volv3d** [comment]
I'm seeing an issue installing via npm as well; verbose failure appears to be around promises here:

Failed at the ng2-cytoscape@0.1.3 postinstall script 'typings install && tsc'

Any help appreciated...

**Comment by hengkyz** [comment]
same problem when i install this module got same error,
any solution yet?

**Comment by d3volv3d** [comment]
My current workaround kinda goes against the spirit of the thing -- I'm importing CytoScape direct at index, then declaring where I need it:

declare var cytoscape:any;
declare var dagre:any;

But it'd be great if we could go native with this. Michael, is there anything we can do to help?

**Comment by hengkyz** [comment]
i already fork this module and i remove the "postinstall": "typings install && tsc" in the package.json,
i succeed install the module, but after i try the example script error anywhere,
lol
can you share how you do it?
btw you can explore this module too,
https://github.com/swimlane/ngx-charts-dag

**Comment by d3volv3d** [comment]
My point would be that I'm not using the module as it currently exists, since I couldn't get it to stand -- much as I'm looking forward to doing so. I'm currently using the dependency driven method of doing things. So, in your index file, you'd have something like this:

<script src="https://cdnjs.cloudflare.com/ajax/libs/cytoscape/2.7.16/cytoscape.js"></script>

Then, in the component where you want to use CytoScape, you declare freeform:

declare var cytoscape:any;

**Comment by michaelknoch** [comment]
are you using typescript or javascript? @d3volv3d @hengkyz @jaags

**Comment by hengkyz** [comment]
@michaelknoch i'm trying 2 of them
but none of them succeed,

**Comment by michaelknoch** [comment]
it seems that there is a new way of resolving typings directly from npm and the old typings cli becomes deprecated. I commited a quickfix and updated the npm package, so the typings should be resolved. Can you check this @hengkyz 

edit: these typings are weird, i pushed the dist folder with transpiled js, d.ts and map files so you can directly use it without running postinstall
